[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.21"
optimizer = true
optimizer-runs = 10_000_000


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
